### ISSUE TITLE
Developer Community posts that prompted me to write Start Page+

### ISSUE THREAD

**Issue by yannduran** [luminous-software/start-page-plus#1]
# Goals for Start Page+

I've tried to capture the pain points, features, requests, feedback etc that have come out of the [Developer Community](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=start+page) posts listed below. 

_The checked ones have already been addressed by Start Page+, the rest may become features in the future._

## User Stories
  - [x] should not be _modal_
  - [x] should not _impede workflow_
  - [x] should not be accessed via _File | Start Page_ ( _View | Start Page+_)
  - [x] should not force extra clicks ([Angelbane Na](https://developercommunity.visualstudio.com/users/142182/624108ef-ead5-4d1b-8f08-63afa5c74eed.html))
  - [x] should be _dockable_
  - [ ] should be _customisable_
  - [x] should cater for '_newbies AND oldbies_'
  - [x] should keep functionality of new _Start Window_ (best of both worlds)
  - [x] should have a list of '_recently used projects/solutions_'
  - [x] should have '_grouping by timeframe_'
  - [x] should have '_Continue Without Code_'
  - [x] should be able to find and read '_Continue with No Code_' easily
  - [x] should have a '_Developer News_' feed ([Evgenij Vrublevskij](https://developercommunity.visualstudio.com/users/89507/c944fed7-83a4-61dd-bce3-37a692b034c5.html))
  - [ ] should be able to _hide_ the 'Developer News' feed
  - [ ] should be able to create a '_Temporary Project_' (WMJ)
  - [ ] should be able to '_group projects together_' (not just recent projects list) ([Leigh Bird](https://developercommunity.visualstudio.com/users/128654/3928f23c-813f-4d13-89f6-18a807162313.html))
  - [ ] could have a checkbox along the lines of "_don't ask me again_" or "_don't notify me again_"
  - [ ] could have the option to '_switch back to the old page_'
  - [ ] could have the option to '_not re-open after closing solution_'

## Developer Community Posts
- [Start Page: Please give it back!](https://developercommunity.visualstudio.com/idea/434456/start-page-please-give-it-back.html) - [_Bernd Müller_](https://developercommunity.visualstudio.com/users/128051/1954e8a4-5370-4f08-a319-0f07284db38e.html)

- [​Make the Visual Studio 2019 start window non-modal](https://developercommunity.visualstudio.com/idea/435168/make-the-visual-studio-2019-start-window-non-modal.html?childToView=734365) - [_jukka_](https://developercommunity.visualstudio.com/users/113805/b0cc5082-b394-623a-9f43-0156f823e647.html)

- https://developercommunity.visualstudio.com/idea/399833/bring-back-the-developer-news-on-startup.html
- https://developercommunity.visualstudio.com/idea/443553/start-window-no-longer-show-projects-grouped-by-ti.html

- https://developercommunity.visualstudio.com/content/idea/435168/make-the-visual-studio-2019-start-window-non-modal.html

- https://developercommunity.visualstudio.com/idea/401834/the-startscreen-should-accept-drag-and-drop-from-e.html

- https://developercommunity.visualstudio.com/idea/401494/the-new-project-creation-window-is-too-small.html

- https://developercommunity.visualstudio.com/idea/402319/vs2019-disable-new-start-screen.html

- https://developercommunity.visualstudio.com/idea/534023/dont-automatically-reopen-start-window-after-closi.html

## Comments
- "_Hi Yann, that looks fabulous. If it can be smoothly integrated into VS2019 then it will be a winner and I'll use it for sure!_ " - [_Greg Keogh_](https://developercommunity.visualstudio.com/users/144315/8362ccc1-c1be-42b7-8f5d-140e7991dd87.html)

- "_This looks really nice and what should have been done by the Microsoft Team to start with._" - [_shawn.mehaffie_](https://developercommunity.visualstudio.com/users/152610/33b31763-a33a-4e0e-b6fe-fc0b1c21e664.html)

- "_Yes this looks exactly how Microsoft should've done it from the start. Best of both worlds._" - [_jukka_](https://developercommunity.visualstudio.com/users/113805/b0cc5082-b394-623a-9f43-0156f823e647.html)

**Comment by MagicAndre1981** [comment]
how do I remove an item from recent list? Rightclick like in VS2017 doesn't show up an option to delete entry from recent list

**Comment by yannduran** [comment]
It's coming soon! As a workaround, you can remove them from the Start Window, and the results will show up in Start Page+ (you may need to use the Refresh button).

**Comment by MagicAndre1981** [comment]
> It's coming soon! As a workaround, you can remove them from the Start Window, and the results will show up in Start Page+

this is what I also discovered

**Comment by yannduran** [comment]
André, could you open an issue called "Feature Suggestion: _Have a way to remove an item from the Recent Items_ list"? 

I'd rather have your name as the owner of the issue than mine, with me then quoting you as the source. 

Thanks!

**Comment by MagicAndre1981** [comment]
> André, could you open an issue called "Feature Suggestion: _Have a way to remove an item from the Recent Items_ list"?

done here: 

https://github.com/luminous-software/start-page-plus/issues/35

**Comment by MagicAndre1981** [comment]
>  should be able to hide the 'Developer News' feed

will this be added in 1.1? @yannduran

**Comment by yannduran** [comment]
I'll have a look at it for you.

**Comment by MagicAndre1981** [comment]
> I'll have a look at it for you.

thanks. Please also make the buttons in "Get Started" smaller?

![startpage_plus_get_started](https://user-images.githubusercontent.com/8274816/83633627-8b15c980-a5a1-11ea-8867-46c25f936706.png)

This size only makes sense when using touch device like Surface Pro. With removal of developers news the size "Open recent items" can be made larger.

**Comment by yannduran** [comment]
Feel free to open an issue for this, but I have to be honest, I don't really like the idea. I don't think it'd look very good.

**Comment by MagicAndre1981** [comment]
currently it looks horrible and wastes space

**Comment by yannduran** [comment]
Gee thanks :-(
