### ISSUE TITLE
Colours are not taking from the theme

### ISSUE THREAD

**Issue by rogerfar** [luminous-software/start-page-plus#10]
I'm using a custom theme that mimics the VS2017 blue theme, but the startpage looks like this:
![image](https://user-images.githubusercontent.com/1142915/65711843-00182300-e053-11e9-9b9d-e43582d3ece6.png)
Is this because there is only dark theme support?

**Comment by yannduran** [comment]
The colors are actually taken from the theme, but currently only the _Dark_ and _Light_ themes are producing acceptable colors. While Start Page+is in preview, I'm snowed under working on the next preview, and the rest of the features that I want to add.

I spent a LOT of time trying to find keys that worked well in all 3 major themes, but I could only manage to get 2 out of the 3 working well. If you'd like to read more about the color situation, you can find a discussion and my explanation in [issue #2](https://github.com/luminous-software/start-page-plus/issues/2), plus it has the `VsColors` keys that I use (if you want to try to find something that works in all 3 major themes) as well a temporary workaround until I can find time to find better `VsColor` keys.

You can always change the colors in _Tools | Options | Environment | Fonts and Colors_ too.

**Comment by yannduran** [comment]
I'm going to close this issue, in favor of [issue #2}(https://github.com/luminous-software/start-page-plus/issues/2),

Thanks!

**Comment by yannduran** [comment]
Preview 2 has been released with a fix to this issue.
