### ISSUE TITLE
"Continue without code" may be redundant

### ISSUE THREAD

**Issue by yannduran** [luminous-software/start-page-plus#19]
Reported by: Greg Keogh (@gfkeogh)

![image](https://user-images.githubusercontent.com/2031126/65936259-6fc94c00-e45f-11e9-9392-36c702e1cd4f.png)

**Comment by yannduran** [comment]
Start Page+ was intended to blend the **_intentions_** of the _VS 2019 Start Window_ with the **_much loved features_** of the now defunct _VS 2017 Start Page_.

I initially had this at the bottom of the column, but I replaced that with the _version number_ link, which takes you straight to the _changelog page_ on the _Start Page+_ website.

I hoped the link would be useful for when a new version is installed, for people to be able to see **_what's changed_**. The version link also let's you **_see at a glance_** what version you have installed without having to hunt for it.

This item is intended to be for people to be able to **_quickly and easily_** dismiss the start page (& yes I realise you can do that with the close button lol). 

I wanted _Start Page+_ to be **_more_** than either the _VS 2017 Start Page_ or the _VS 2019 Start Window_, without **_losing_** anything from either.

That said, I'm happy to entertain the idea of adding an option to hide it (for people who don't want to see it) at a later time.

**Comment by MagicAndre1981** [comment]
remove it, it is useless

**Comment by yannduran** [comment]
You're right André! I finally realised it myself.
