### ISSUE TITLE
A project with spaces in the name throws an error when opening it

### ISSUE THREAD

**Issue by jcgperry** [luminous-software/start-page-plus#23]
### Installed product versions
- Visual Studio: 2019 Community v16.3.1
- This extension: v0.14.3

### Description
Attempting to open a Recent Item (a .csproj file) with spaces in the path results in the error: "Command allows at most one argument"
However, opening the .sln file containing the same .csproj works as expected.

**Comment by yannduran** [comment]
Ahh, yes I didn't think of that, as I never have spaces in my project names. I'll have to see if it's as simple as just surrounding the project name with quotes. 

This should be fixed in the _next preview_.

**Comment by yannduran** [comment]
I changed the name of this issue, I hope you don't mind.

**Comment by yannduran** [comment]
I've implemented a fix for this, which will be available when Preview 4 is released.
