### ISSUE TITLE
Bug: Page does not open if separate Developer News extension is loaded.

### ISSUE THREAD

**Issue by Kuffs2205** [luminous-software/start-page-plus#3]
Reporting only so it is documented for others. I don't think it needs fixing as it's unlikely that both extensions would be normally installed given that SPP has its own New section.

### Installed product versions
- Visual Studio: 2019ENT
- This extension: 0.12.1

### Description
The original "Developer News" extension by the same author causes the "View Start Page+" menu button to not work if installed at the same time

### Steps to recreate
1. Install both extensions

### Current behavior
Start page does not open

### Expected behavior
Start page opens

**Comment by yannduran** [comment]
Thanks for taking the time to document this!

That's weird, as I have both extensions installed and it opens for me. The issue that I AM aware of is if you close _Start Page+_ it currently won't open again until you restart VS. I haven't been able to figure out why yet.

**Comment by Kuffs2205** [comment]
Possibly something conflicts that is unique or common to my setup.  I can only say that pressing the menu item to open the start page did nothing until I disabled the News extension.

Re-enabling the news extension again makes the start page not open.

Like I said, not really important but the fact it is documented may mean that someone doesn't spend ages trying to work out why the start page doesn't work.

**Comment by Kuffs2205** [comment]
Actually, re-reading your final comment. SP+ only opens automatically for me if it is already open when Visual Studio closes.  If it wasn't already open, I have to use the menu item.  I figured this was because its only an early preview.

**Comment by yannduran** [comment]
Yes, I need to compile a list of _known issues_ so that people can read about the current _preview_ type behavior.

Btw, did you download this from the _Marketplace_, or from _Manage Extensions_? Again, just out of curiosity, if you saw the Marketplace page did you read the preface I put at the top of the extension?

I was planning on putting the compiled list of _known issues_ on _Start Page+_'s website, but if most people don't know it exists, that may not be the best idea. Hence my questions.

Thanks!

**Comment by Kuffs2205** [comment]
I got it directly from the VS UI, i.e Manage extensions. Sorry, I didn't know there was a web site until just now when I read the Github readme and spotted the link within.

**Comment by yannduran** [comment]
Is this still an issue that you feel needs to remain open? Would you mind if we closed it if not? I'd like to keep the list of _open issues_ as short as possible. We can always re-open it if you can confirm that it's still a problem. I really haven't had time to look into this myself. 

I have them both installed and working fine (_SP+ 0.14.3.1_ & _DN 1.1.0.2_ ). I compare the _Developer News_ of both extensions from time to time, to make sure that they match.

**Comment by Kuffs2205** [comment]
I no longer have that other extension installed so I don't mind at all.  I only created it as I thought it may be reported by others who couldn't find the solution as quickly.  Thanks.
