### ISSUE TITLE
Feature Suggestion:  Have a way to remove an item from the Recent Items list

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus#35]
It would be nice to have a way to remove an item from the recent projects list

**Comment by MagicAndre1981** [comment]
@yannduran do you still work on it? Does the extension work with 16.4 (preview)?

**Comment by MagicAndre1981** [comment]
looks like the project is dead or do you still work on it @yannduran ?

**Comment by yannduran** [comment]
hi @MagicAndre1981. 

no, the project isn't _dead_. i **do** intend to work on it.

i've just had a very hard time adjusting to life on my own, after losing my loved one. we shared each day together for so long, and suddenly it's just me. it's just hard.

i haven't written a single line of code since it happened, but i do hope to get back to coding again soon.,

**Comment by MagicAndre1981** [comment]
ok, I'm sad to hear this 😢🙏🕯️🤗

**Comment by yannduran** [comment]
thanks André!

**Comment by yannduran** [comment]
v1.0 will include this feature - see [Milestone v1.0](https://github.com/luminous-software/start-page-plus/issues?q=is%3Aissue+milestone%3Av1.0+)

**Comment by MagicAndre1981** [comment]
@yannduran any ETA for version 1.0? I guess MS will release 16.6 update a Build tomorrow, will 1.0 work?

**Comment by yannduran** [comment]
I've revised the due date to this coming Friday just to be safe, but it could also happen in the next couple of days. But definitely this week. I've got all but one of the GitHub issues sorted, except for one very trivial one. I'm now working on getting as much as I can of my own backlog into the v1.0 release.

I don't see any reason why it wouldn't work with 16.6, I'm just installing the 16.6 Preview 6 right now and I'll install and test with it tomorrow, but I'm not expecting any problems. As soon as I can download and install 16.6 GA I'll test with that too. I'm not exactly sure how the time zones will line up. Hopefully it'll be available when I wake up tomorrow. I'm off to bed very soon.

**Comment by MagicAndre1981** [comment]
MS is known to make changes only to break 3rd party tools that fix their wrong design changes.

**Comment by yannduran** [comment]
Test on 16.5.4 & 16.6 Preview 6, all seems fine. I'm dogfooding each revision as I go.

**Comment by MagicAndre1981** [comment]
because you were not active, I stayed at 16.4 which is long servicing release and here your extension worked. So I can update to 16.6 when it gets released.

**Comment by yannduran** [comment]
>because you were not active

Yeah, I'm sorry about that. But I know you understand why that was.

**Comment by MagicAndre1981** [comment]
> But I know you understand why that was.

yes, I do 🤗

**Comment by MagicAndre1981** [comment]
extension works on 16.6 (stable channel)

**Comment by yannduran** [comment]
Thanks for the confirmation.

**Comment by yannduran** [comment]
@MagicAndre1981 

I've tried hard to meet my stated deadline of this week, but I've had back problems which have limited my time at the keyboard unfortunately.

My sprints are based on calendar months, so my current sprint ends May 31. So I'm going to align my release date for _v1.0_ to that (ie release by June 1st). Hopefully that'll give me the time I need to finish up what I've been working on.

Sorry. I want this out there as much as anyone!

**Comment by MagicAndre1981** [comment]
@yannduran this fine, as current version works.

**Comment by MagicAndre1981** [comment]
@yannduran ok works fine in 1.0. I can pin, unpin and remove solutions from list 👍

**Comment by yannduran** [comment]
Great to hear!
