### ISSUE TITLE
All removed shortcuts reappear

### ISSUE THREAD

**Issue by Kuffs2205** [luminous-software/start-page-plus#39]
### Installed product versions
- Visual Studio: 2019
- This extension:1.0

### Description

I cleaned up the Start Page by removing all old unused projects.  They reappear after a couple more launches of VS

### Steps to recreate
1. Remove shortcut
2. Close VS and Reopen a couple of times

**Comment by yannduran** [comment]
Hmmm, I missed that. Thanks for letting me know. I already knew that it wasn't syncing with the *Start Window*, but I figured people using *Start Page+* wouldn't be using the *Start Window*, so I put it on my list to investigate.

I guess this is another symptom of the same problem, so I'll be looking into it. I didn't notice it in my own testing. Sorry about that.

**Comment by Kuffs2205** [comment]
I actually thought this had righted itself as I could not get the removed shortcuts to reappear again yesterday.  Unfortunately, they all returned again today. FWIW, I don't care it it syncs with the Start Window or not.  I'd rather go with the "File->Open" menu that use that horror.

**Comment by yannduran** [comment]
Updating how I get/update recent items was already on my list. When I get that done, this problem should disappear.

**Comment by yannduran** [comment]
@Kuffs2205 I've just recently noticed this happening myself. I don't know if something changed in a VS release.

But the method that I was using to manage the recent items was not supported. So my intention is to use a different way now.
