### ISSUE TITLE
Space in Solution Path - Can't Open Solution from Recent Items

### ISSUE THREAD

**Issue by BOBJohnson** [luminous-software/start-page-plus#43]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 1.0

### Description
Cannot open a solution from the Recent Items if there is a space in the path to the item.

### Steps to recreate
1. Create a solution that has a space in the path.
2. Refresh the recent items to make sure the item shows up in recent items.
3. Try to open the recent item with the space in it.

### Current behavior
If I try to open a solution from the Recent Items, and it has a space in the Path, it will give the following popup message:

Can't find '"C:\Users\<username>\source\repos\Test Space\TestSpace.sln"'.

### Expected behavior
The recent item to open anyway.

Note that spaces in Preview 3 was not an issue.

PS. I'd appreciate if this could be fixed rapidly. I unfortunately have numerous recent items that have spaces in them - include several pinned common Solutions. I'm going to have to roll back to Preview 3 (if that's even possible) if it doesn't get fixed quickly.

PSS. Was happy to see a new update today. Glad to see this project is still alive.

**Comment by yannduran** [comment]
I'm sorry about this Bob, a refactor caused a regression bug, and it somehow got passed me, even though I was sure I had tested for that problem specifically.

Issue #38 is also about the same thing and was closed as _fixed_, so that's probably why you didn't see it. The original issue was #23.

It's been fixed, and I'll have the update out soon (_v1.0.1_).

**Comment by BOBJohnson** [comment]
Thanks!

**Comment by BOBJohnson** [comment]
Just downloaded the new version. Fixed. Thanks!

**Comment by yannduran** [comment]
That great Bob! Thanks for the confirmation :-)
