### ISSUE TITLE
 Recent Item accessed date not the expected date

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus#45]
> but a quick test shows that the pin status didn't get lost after closing and re-opening VS.

> I'm  not sure what you mean by:

> > _doesn't show correct last usage time_

> Are you saying that it used to show the last opened date correctly, but now doesn't?

I noticed that I had 1 project opened on friday, which was 2020-06-19, but recent item showed 2020-06-16

_Originally posted by @yannduran in https://github.com/luminous-software/start-page-plus/issues/37#issuecomment-647531900_

**Comment by MagicAndre1981** [comment]
today I checked the list and I see the recent items from yesterday. So sometimes it fails to update the data.

**Comment by yannduran** [comment]
@MagicAndre1981 I think I may have found somewhere that the dates aren't being processed properly. I'll have a look at it tomorrow.

**Comment by MagicAndre1981** [comment]
ok, can it be a locale issue? I use de-DE for Windows 10 and an en-US Visual Studio 2019

**Comment by yannduran** [comment]
I think it's something along those lines, but it won't be the locale that you're using for Windows.

**Comment by MagicAndre1981** [comment]
it worked a few days, today my pinned items from last week are gone. but some old item from some time ago (which I likely pinned with Start Window before your extension was able to do it) are always pinned.

**Comment by yannduran** [comment]
Pinned items disappearing/reappearing is not the same problem as the last accessed date not displaying correctly. Anybody looking to see if anyone else has this problem will not find it buried in here.

Please open a new issue for it. Unrelated problems need their own issue. I've mentioned this before.

**Comment by MagicAndre1981** [comment]
I think this was a Visual Studio 2019 bug. I haven't see the unpin and wrong date issue for a longer time.

**Comment by yannduran** [comment]
That's great to hear André! Thanks for coming back to let me know.

I'll close this issue, but feel free to open re-open it if you encounter the problem again.
