### ISSUE TITLE
Bug: Recent Item Timeframes Disappear When Refresh is Clicked

### ISSUE THREAD

**Issue by yannduran** [luminous-software/start-page-plus#5]
### Description
In the 'Recent Items' list, when 'Refresh' is clicked, the timeframes disappear.

### Steps to recreate
Click 'Refresh'button in the 'Recent Items' list.

### Current behavior
Timeframes disappear and they should always be there.

### Expected behavior
Timeframes should never disappear.

### Workaround
Click on a different tab, then click on the 'Start' tab.

**Comment by NetMage** [comment]
The Pinned Items also disappear when Refresh is clicked.

**Comment by MagicAndre1981** [comment]
> The Pinned Items also disappear when Refresh is clicked.

yes, this is what I also see. They are no longer on top, but added to list based on their last usage time.

**Comment by yannduran** [comment]
@NetMage , @MagicAndre1981 you guys are right! I hadn't even noticed that.

You'll be pleased to know that I'm back writing code again, and I recently found the cause of the bug, and am dogfooding the fix at the moment. So far no problems with it.

I'm currently working on _pinning_ and _unpinning_ items. Then will come _removing_ items. Once those two are completed, I'll release **v1.0** which will include the fix for the disappearing timeframes, the two completed features, plus a couple of new minor settings.

**Comment by yannduran** [comment]
v1.0 will include this fix

**Comment by MagicAndre1981** [comment]
> You'll be pleased to know that I'm back writing code again, and I recently found the cause of the bug, and am dogfooding the fix at the moment. So far no problems with it.

nice to hear that you're back 👍

**Comment by yannduran** [comment]
Sorry André, I thought I had replied. Thanks! It's good to be back.

I've been very busy working on the v1.0 release. You can see the progress in [Milestone v1.0](https://github.com/luminous-software/start-page-plus/milestone/5)
