### ISSUE TITLE
Update Start Page+ to use the new Visual Studio Community Toolkit

### ISSUE THREAD

**Issue by yannduran** [luminous-software/start-page-plus#51]
[Visual Studio Community Toolkit](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit)

**Comment by MagicAndre1981** [comment]
don't do this, as it currently causes issues, [when different extensions use different versions of the toolkit ](https://github.com/madskristensen/Tweakster/issues/76)

**Comment by yannduran** [comment]
I'm following the discussion about this in the Community Toolkit repo.

A Start Page+ update won't be issued until the issue is resolved.
