### ISSUE TITLE
VS2022 support

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus#55]
### Installed product versions
- Visual Studio: 2022 Enterprise Preview 1

### Description

The extension should work with VS2022 preview 1

### Steps to recreate
1. install VS2022 preview
2. search in VS for Extension 

### Current behavior
StartPage+ is missing

### Expected behavior
StartPage+ shows up and can be installed

**Comment by yannduran** [comment]
I just got the preview today. I'm right in the middle of a lot of internal reworking of the code (nothing to do with 2022). I'll have it up as soon as I can. I miss it too.

**Comment by MagicAndre1981** [comment]
can you please push your local changes so that we can try it on our own if you don't have any time? @yannduran

**Comment by LeadMagnet** [comment]
Any chance on an update or that progress branch?

Company migrating to Windows 11 and VS2022 over the holiday break. This extension is on the list of "required" :P

**Comment by MagicAndre1981** [comment]
I doubt that we ever get a working version. @yannduran is gone  for months. Current code depends on his own package that provides an AsyncPackage implementation that depends on removed code in VS2022, so current codebase doesn't work,

**Comment by MagicAndre1981** [comment]
Happy new year @yannduran . I hoe you're fine and please provide VS2022 support. It is unusable at all without your extension.

**Comment by yannduran** [comment]
Thanks André! I'm sorry I've been MIA for a while. I haven't been very well.

I'm able to do a little work at my desk recently, and I've started on porting Start Page+ to VS 2022. It's been a bit complicated, but it's going well. I have more to do though before it's ready to be tested.

I agree with you. VS 2022 is pretty unusable with SPP. I miss it so much as I'm trying to port the code.

**Comment by MagicAndre1981** [comment]
yeah,  @yannduran is back 🥳

can you push your changes in an extra brach so that we can see progress and get early previews?

**Comment by MagicAndre1981** [comment]
I can't download the[VS2022 64 bit version](https://www.vsixgallery.com/extension/96b389fd-48b6-48d9-bbf2-ec6ebd026b14):

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by MagicAndre1981** [comment]
ok, [this link](https://www.vsixgallery.com/extensions/96b389fd-48b6-48d9-bbf2-ec6ebd026b14/extension.vsix) works, but StartPage+ doesn't work in VS2022 17.2 Preview 1:

`Construction of frame content failed. Frame identifier: ST:0:0:{e3be6dd3-f017-4d6e-ae88-2b29319a77a2} Frame caption: Start Page+ Exception details: System.Windows.Markup.XamlParseException: Set property 'System.Windows.ResourceDictionary.Source' threw an exception. ---> System.IO.IOException: Cannot locate resource 'resources/brushes.xaml'. at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access) at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access) at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream() at System.IO.Packaging.PackWebResponse.get_ContentType() at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response) at System.Windows.ResourceDictionary.set_Source(Uri value) at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value) --- End of inner exception stack trace --- at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri) at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream) at StartPagePlus.UI.Views.MainView..ctor(ToolkitPackage package) in D:\a\start-page-plus-64-bit\start-page-plus-64-bit\src\vsix\UI\Views\MainView.xaml.cs:line 16 at StartPagePlus.UI.ToolWindows.MainWindow.CreateAsync(Int32 toolWindowId, CancellationToken cancellationToken) in D:\a\start-page-plus-64-bit\start-page-plus-64-bit\src\vsix\UI\ToolWindows\MainWindow.cs:line 26 at Community.VisualStudio.Toolkit.ToolkitPackage.<InitializeToolWindowAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass33_0.<<Microsoft-VisualStudio-Shell-Interop-IVsAsyncToolWindowFactory-InitializeToolWindowAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c__DisplayClass54_0.<<CancelWhenCancellationRequested>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.<>c__DisplayClass54_0.<<CancelWhenCancellationRequested>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) at Microsoft.VisualStudio.Shell.AsyncPackage.<CompleteToolWindowCreationAsync>d__38.MoveNext()`

**Comment by yannduran** [comment]
Thanks @MagicAndre1981 - I'll have a look at that. I've only been running it in VS 2022 17.1 experimental instance so far and hadn't seen that issue.

"_Cannot locate resource 'resources/brushes.xaml'_" is the problem, so at least I know what to look for.

The link I gave you for the preview was before I started using version numbers in the vsix name, so that may be why the link didn't work. If you haven't already done so, make sure you install Mads Kristensen's [Open VSIX Gallery](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds) extension to automatically get access to future preview CI versions published to the gallery.

I think I mentioned it in another of your threads, but I'll say it again here. The current preview versions are **_not yet functional_**, they only display the UI. A couple of the links at the bottom of the page work, but subsequent previews will continue to add functionality.

**Comment by MagicAndre1981** [comment]
> Thanks @MagicAndre1981 - I'll have a look at that. I've only been running it in VS 2022 17.1 experimental instance so far and hadn't seen that issue.

I just installed a fresh 17.1 copy and it also doesn't work:

![image](https://user-images.githubusercontent.com/8274816/155857560-2dad386a-9c38-4c4a-b0dd-c259d49444c7.png)

I use German x64 Windows 11 22000.493 and VS2022 Enterprise with EN-US language pack.

**Comment by MagicAndre1981** [comment]
any update on my issue with the test version?

**Comment by MagicAndre1981** [comment]
any update on my issue or are you again ill to be not able to work on it?

**Comment by MagicAndre1981** [comment]
looks like @yannduran is gone again. Now that .net5 is EOL and 3.1 will be EOL later this year, VS2019 is dead and we need a VS2022 solution. Can you please push your VS2022 changes so that I can debug it on my own?

**Comment by MagicAndre1981** [comment]
@yannduran Please push your VS2022 changes so that I can debug the issue on my own and have at least a somehow working StartPage. VS2022 is currently unusable without your extension 🙏 🙏 😇

**Comment by MagicAndre1981** [comment]
I saw that you made a fork @yannduran  Please push your VS2022 changes so that I can debug the issue on my own

**Comment by MagicAndre1981** [comment]
ok, in VS2022 17.6 a Welcome page can be enabled as preview:

![image](https://user-images.githubusercontent.com/8274816/222967981-692bb8ae-bb19-4e18-8e86-442ba6f9c0ca.png)

Your one is still better in layout, but at least I a have a somehow working solution in VS2022

**Comment by MagicAndre1981** [comment]
ok, with Preview 2 Microsoft changed the layout and made it better: 

![image](https://user-images.githubusercontent.com/8274816/225882625-670e5f8f-57c6-4679-95ce-be3598b0bd7c.png)

I can live with their solution. 

To enable it in 17.6 Preview 2, go to Options->Preview Features and selct the checkbox for "Welcome page"

![image](https://user-images.githubusercontent.com/8274816/225882983-932feef7-211e-4393-b062-7a30338d4d5a.png)

@yannduran do you still work on your StartPage?

**Comment by MagicAndre1981** [comment]
Microsoft official announced the new welcome page on their blog:

Help us investigate a new Welcome Experience in Visual Studio 17.6 Preview 2
https://devblogs.microsoft.com/visualstudio/welcome-experience/

**Comment by yannduran** [comment]
I'm sorry that I've been MIA for so long André. My health just hasn't given me any time to do much at all, including emails etc.

I've had a slightly better week this last week and I've just about got the basic things working. Recent items now load the clicked solutions/projects, but some of the fancier bits are still to come. Clicked news items now open either in VS or in a the user's browser.  I'm dogfooding it as I go, so I know it installs & opens successfully in both **_VS Community 17.5.3_** & **_Preview 17.6.0 Preview 2_**. And of course the experimental instances of both.

I keep meaning to upload what I've done so far, but then I forget to do it and end up working on another part while I'm still able.  You know that fish in the movie Nemo, that swims around in a circle and keeps forgetting everything. That's how I feel!

There have been some areas where I've **had** to change quite a lot of code, and other things I've **wanted** to change  before it gets uploaded. Things such as having to convert to using the MVVM toolkit (including dependency injection, which I use a lot). I was using MVVMLight, but it got deprecated in favor of the Community Toolkit For MVVM, and it took me a while to get my head around it. My eyesight, attention span, and concentration have all suffered over the last few years, so it can be a bit slow going, and I also get tired easily too. The list goes on & on...

You may not even need to use _Start Page+_ anymore, but I've always wanted to get the 64-bit version working. I'll try to remember to upload when I've finished the changes that are currently in progress. It may not have **full** functionality, but at least the basics will be working. If you want, I can email or message you a working vsix, so you can try out the bits that are working. Just let me know.

Again, I'm sorry it's taken so long to reply to your messages. I REALLY wish I had been able to keep working at my desk for up to 12 hours like I used to. Sadly that's not been the case.

**Comment by MagicAndre1981** [comment]
ok, get well soon.

**Comment by yannduran** [comment]
I wish! But thanks for the thought. I really appreciate it. Unfortunately they're chronic conditions I'm afraid.

**Comment by yannduran** [comment]
Hi Andre, I've created a [start-page-plus-64-bit repo](https://github.com/luminous-software/start-page-plus-64-bit), and added a [v0.19](https://github.com/luminous-software/start-page-plus-64-bit/releases/tag/v0.19) release containing the vsix for you to try.

If you find any bugs, please open a **_bug_** issue in the new repo. If you find some _missing functionality_, please open a **_feature request_** issue in the new repo.

Please only put ONE bug, or ONE piece of missing functionality per issue. This'll make it much easier for me to track, and will help me prioritise what to do when I am able.

There's a single **_develop_** branch for the moment as the code is preview code. Once it's ready I'll add **_master_** branch as well for the production code.

Could you do me a favor?

I can't sign into the the Developer Community site, as I refuse to allow them to add far more permissions than what they should require. If it's ok with you could add a link to the [v0.19](https://github.com/luminous-software/start-page-plus-64-bit/releases/tag/v0.19) preview for VS 2022 to the [Welcome customizations in Visual Studio](https://developercommunity.visualstudio.com/t/Welcome-customizations-in-Visual-Studio/10311633) post, and its related links ([Make the Visual Studio 2019 start window non-modal](https://developercommunity.visualstudio.com/t/Make-the-Visual-Studio-2019-start-window/435168) and [Bring back Developer News on Startup](https://developercommunity.visualstudio.com/t/DevNews/399833))?

If you do, could say that you've been a long-time user of the VS 2019 version that would help too.

TIA and thanks for your patience! We got there in the end.

**Comment by MagicAndre1981** [comment]
thanks, I posted it and it works so far but still requires some work on issues that were also posted here for the 2019 version.

**Comment by yannduran** [comment]
I hadn't gotten around to checking the old version's issues yet. I was focused on getting the code working and getting a preview version out. I'll definitely check them now that you've reminded me, so thanks.

**Comment by yannduran** [comment]
Thanks for posting that! However you forgot to give them a clickable link, & without the actual name `Start Page+` (you called it startpage) they may not find it if they're looking for it.
